### ISSUE TITLE
External links in the footer are wrong

### ISSUE THREAD

**Issue by julian-molina** [AdvancedAlgos/MasterApp#120]
Link URLs seem to be set relative to the platform's root folder, which is incorrect.

Proper links:

- Privacy Statement: https://www.advancedalgos.net/legal-privacy-statement.shtml
- Terms of Service: https://www.advancedalgos.net/legal-terms-of-service.shtml
- Telegram: https://t.me/advancedalgoscommunity
- Twitter: https://twitter.com/advancedalgos
- Facebook: https://www.facebook.com/advancedalgos/

![image](https://user-images.githubusercontent.com/13994516/49001605-7f03ad00-f15d-11e8-83e6-dcb6209360dd.png)

**Comment by bearcanrun** [comment]
Fixed by #126
