### ISSUE TITLE
Link to Documentation must be available on Interface

### ISSUE THREAD

**Issue by julian-molina** [AdvancedAlgos/MasterApp#20]
In order to link the website to the app, we need that people landing at the app have direct and clear access to the documentation.

<a href="https://www.advancedalgos.net/documentation-quick-start.shtml" target="_blank">Documentation</a>

**Comment by Luis-Fernando-Molina** [comment]
![image](https://user-images.githubusercontent.com/9479367/47431468-2aef5c80-d79c-11e8-849e-75a8c7753db1.png)
done
